package-lock.json, package.json, readme.md
- The `git clone` command didn't work with the provided argument
- `npm run vscode:dev` wasn't working on windows since `${PWD}` wouldn't be resolved → added `cross-env` as a dev package to allow the use of env variables in a cross-platform way
=> Fix install instructions

src/core-back/FlowRun.ts
With a workflow like
```ts
... setup
const { images: [img] } = await flow.PROMPT()
await flow.uploadURL(img.comfyURL)
```
you would get a weird error saying `source.on` is not a function.
It seemed to be related to a bad usage of `FormData`
This PR attempts to fix that
Note that
```ts
… setup
graph.SaveImage({ filename_prefix: 'ComfyUI', images: vae })
const { images: [img] } = await flow.PROMPT()
await flow.uploadWorkspaceFile(img.localRelativeFilePath)
```
still currently errors because the image seems to be saved afterwards
I'm not sure if that's normal ? and if so, how could we wait for images to be saved ?
=> Fix bad usage of form-data

src/controls/FormBuilder.ts, src/controls/Widget.ts, src/controls/widgets/WidgetInlineRunUI.tsx, src/controls/widgets/WidgetUI.DI.ts, src/controls/widgets/WidgetUI.tsx, src/panels/Panel_Draft.tsx
This has the same value as a form.bool({}), but it returns true only once when it is clicked. It is designed to be used in a `run` action to run specific parts of code:
Example:
```ts
// ui
previewCrop: form.inlineRun({}),
// run
if (form.previewCrop) {
graph.PreviewImage({ images: cropped_image })
await flow.PROMPT()
return
}
```
---
This also has a fix to the main button to disable the autorun if it is hit.
=> Add InlineRun Widget

_windows_INSTALL.bat
Added quotes around the paths in the .bat file so paths with spaces don't fail
=> quotes in dependency install paths

library/built-in/SDUI.ts, library/built-in/_prefabs/ControlNet/prefab_cnet_canny.ts, library/built-in/_prefabs/ControlNet/prefab_cnet_depth.ts, library/built-in/_prefabs/ControlNet/prefab_cnet_ipAdapter.ts, library/built-in/_prefabs/ControlNet/prefab_cnet_lineart.ts, library/built-in/_prefabs/ControlNet/prefab_cnet_normal.ts, library/built-in/_prefabs/ControlNet/prefab_cnet_openPose.ts, library/built-in/_prefabs/ControlNet/prefab_cnet_scribble.ts, library/built-in/_prefabs/ControlNet/prefab_cnet_softEdge.ts, library/built-in/_prefabs/ControlNet/prefab_cnet_tile.ts, library/built-in/_prefabs/prefab_cnet.ts
Repackaged the cnet UI to allow multiple cnets on one image, and hid advanced settings so it is easier to manage
The second pass sampler change in SDUI is so that when a controlnet is used, the conditioning to the second pass is original (not cnet). Upscaled images look pretty weird when controlled.
=> cnet interface cleanup

src/widgets/prompter/plugins/CushyCompletionPlugin.tsx, src/widgets/prompter/plugins/CushyShortcutPlugin.tsx
Added ALT+UP and ALT+DOWN shortcuts to prompt editor to change text prompt weight
Removed the deep search that was pulling results from wildcard lists instead of just the titles of completion objects
=> Prompt-widget-improvements

src/controls/widgets/number/WidgetNumber.tsx, src/controls/widgets/number/WidgetNumberUI.tsx, src/controls/widgets/prompt/plugins/Plugin_AdjustWeights.tsx, src/controls/widgets/size/WidgetSizeUI.tsx, src/rsuite/InputNumberUI.tsx, src/theme/theme.css
We counted higher than Valve edition.
Changes to \<InputNumberUI/\>
- Add suffix option
- Set the input type to text, so the input will allow you to type whatever you want.
- Attempted fix for sliders being agonizing to drag for people with low sensitivity set for their mouse.
It does this by attempting to pass {unadjustedMovement: true} to requestPointerLock(), which should get the raw mouse input instead of processed mouse input. This will not fix the issue for people on Linux as Chromium hasn't implemented the option to work there yet.
=> Relative sliders part THREE!!!

src/widgets/misc/MsgShowHTMLUI.tsx
Pressing escape will hide the GalleryHoveredPreviewUI if it is active
=> Temporary workaround for stuck overlay

library/built-in/CushyDiffusion.ts, library/built-in/_prefabs/prefab_model.ts
Models I use often have an override config. ComfyUI's function to 'guess config' does not work like Automatic's, which loads a config yaml by the checkpoint name.
In Comfy, the SimpleCheckpointLoader does not do this, it instead scans the unet_config in the checkpoint itself and then compares it to a list of known architectures before picking one.
If you want to use a model which comes with a separate config, as many experimental V-Prediction models do, you have to use the frighteningly named (deprecated) CheckpointLoader. 
In this PR I add to the built in Cushy Diffusion an extra button to indicate a config, which then triggers the other loader in the run step.
Coincidentally such models also tend to need CFGRescale, so I added another extra config to enable that node in the graph as …
=> Add support for custom ckpt config and CFG rescale

library/built-in/_prefabs/prefab_latent_v3.ts, src/controls/widgets/choices/WidgetChoicesUI.tsx, src/controls/widgets/size/WidgetSize.ts, src/controls/widgets/size/WidgetSizeTypes.ts, src/theme/theme.css, tailwind.config.js
- text-shadow and text-shadow-inv option for tailwind/className.
- use this to have the UI not look as bad when dark on light text.
- Add default options for dimensions of size widget, also makes it so just setting the modelType will use the model's size
=> Quick Tweaks

library/built-in/_prefabs/prefab_latent_v3.ts, src/controls/widgets/WidgetSelectOneUI.tsx, src/rsuite/InputNumberUI.tsx, src/rsuite/SelectUI.tsx, src/theme/theme.css
InputNumberUI
- Move as much as possible from raw CSS to Tailwind
- Can now use mouse to select text, also trying to select selected text will not start a drag and drop.
- Moved things around a bit, could still probably be cleaned up a bit more
SelectUI
- No longer can be too large and go off-screen
- CSS adjustments
Note: Need to work out how to make it not close on click, so people can use the mouse to drag the scrollbar. Not a big deal as I don't *think* there's a menu that will have that many options though, or someone without a scroll-wheel in 2024.
SelectOneUI
- Add the new text-shadow/inv
Get rid of the mistakenly set modelType default for the latent_v3 prefab
=> UI: Overhaul InputNumberUI (again), improve Search enum widget, and minor changes

src/models/MediaImage.ts, src/panels/ImageDropdownUI.tsx
Also adds a button to "send to clipboard" in ImageDropdownUI
As far as I can tell, you can only put png/jpg's in the clipboard, so it must be converted always.
This more than likely won't keep any image metadata, but it's useful for quick sharing. Most chat applications scrub metadata nowadays anyways.
=> MediaImage: Add copyToClipboard function

src/controls/widgets/choices/WidgetChoicesUI.tsx, src/controls/widgets/enum/WidgetEnumUI.tsx, src/controls/widgets/number/InputNumberUI.tsx, src/controls/widgets/selectMany/WidgetSelectManyUI.tsx, src/rsuite/SelectUI.tsx, src/theme/theme.css
This only fixes the UI itself, not the underlying functionality. Makes it looks like how searchEnum looked, by moving most the changes I made there to this file instead.
- Added a WIDGET-FIELD class to theme.css, to make all the input widgets have a consistent height in the future
- Use the new checkbox styling
- InputNumberUI now uses the WIDGET-FIELD class
=> UI: Fix SelectUI Visually (selectMany/searchEnum)

src/controls/widgets/string/WidgetStringUI.tsx, src/theme/theme.css
- Changes to be more visually like InputNumberUI & SelectUI
- Uses the new WIDGET-FIELD to make height consistent
- Input can now be cancelled, and will use the previous value like how typing with InputNumberUI functions. (Clicking off or pressing enter accepts the input)
- Added `WIDGET-FIELD *::selection` css, to make highlights for text consistent.
=> UI: Varius UI/UX tweaks

library/built-in/_prefabs/prefab_latent_v3.ts, src/controls/widgets/number/InputNumberUI.tsx, src/controls/widgets/seed/WidgetSeedUI.tsx, src/controls/widgets/size/WidgetSizeUI.tsx, src/panels/router/Layout.tsx, src/widgets/galleries/ImageUI.tsx
RIP I'm tired, first commit is for WidgetSizeUI
WidgetSizeUI
- Made the aspect ratio display centered and darker background
- Use join/join-item to connect width/height/aspect ratio lock
- Update the latent_v3 prefab to get rid of borders
- Slight CSS tweaks
InputNumberUI
- Fix padding
WidgetSeedUI
- Make buttons similar colors to other newer buttons
- Make consistent size
- Use InputNumberUI instead of InputNumberBase
- Use icons instead of emoji
- Slight CSS tweaks
Misc
- Middle mouse closes tab
- Middle mouse opens image in a dedicated panel
=> UI: Improve SizeWidgetUI, fix InputNumberUI, overhaul SeedWidgetUI

src/controls/shared/WidgetWithLabelUI.tsx, src/controls/shared/Widget_ToggleUI.tsx, src/controls/widgets/bool/InputBoolUI.tsx, src/controls/widgets/bool/WidgetBool.tsx, src/controls/widgets/bool/WidgetBoolUI.tsx, src/controls/widgets/choices/WidgetChoicesUI.tsx, src/controls/widgets/optional/WidgetOptional.tsx, src/rsuite/SelectUI.tsx, src/rsuite/reveal/RevealUI.tsx, src/theme/theme.css
- Moves logic to \<InputBoolUI\> so that it's easily re-usable as a checkbox for other widgets
- Adds a deprecation warning for label2 on Widget_BoolUI, it should be replaced with the new text option
- Dragging to make checkbox share a similar state when you drag over them should work with more areas now that more things will use the same underlying widget instead of duplicated code. (Only WidgetBoolUI, Widget_ToggleUI, and SelectUI (search enum, choices) with this PR)
- `expand` Makes the widget use as much space as possible (horizontally)
- `icon` Uses a material-symbols-outlined icon name (Not sure how to type this correctly so it's just a string, but displaying all the icon names would be cool)
- `display` Sets the way the widget is displayed
- - `check` gives you a normal checkbox, …
=> UI: Overhaul Boolean widget, Improve SelectUI/Panel UX

src/controls/widgets/prompt/plugins/Plugin_LoraBoxUI.tsx
- It will now delete the surrounding weighted expression
*NOTE: Only if the lora is the only thing in the expression*
- This also cleans up trailing whitespace/commas
- Adjusting the weight will make a new WeightedExpression around the
lora instead of adjusting a parent's weights
=> Improve Plugin_LoraBoxUI's UX

src/models/MediaImage.ts, src/shell/main.js, src/utils/electron/ElectronUtils.ts, src/utils/misc/toasts.ts, src/utils/misc/toasts.tsx
- Use Electron's api to do the operation instead of the Browser's
- No longer needlessly converting buffers, so should be way faster
- Will always work, even if the window becomes un-focused
- New toast for displaying the copied image
This may be a bit sloppy.
=> Improve copying image to clipboard

library/built-in/CushyDiffusion.ts, library/built-in/_prefabs/prefab_model.ts
1. Added perturbed attention guidance
Can improve attention at the cost of performance.
Support for both base pass and hires pass
(there is a breaking change for any existing app using run_model that SAG won't be included anymore, refer to CushyDiffusion for new method)
2. Added Kohya Deep Shrink
Can adapt models to higher resolution than training, and helps with coherence for non-tiled hires fix. Example use: SD1.5 generate 2048x2048 using kohya scale of 4. Or upscale 512x512 4x on hires fix with less artifacts.
3. Added selection to SAG to choose if it applies to base or hires pass
=> Model Modifiers - Perturbed Attention and Kohya Deep Shrink

src/controls/widgets/number/InputNumberUI.tsx
- The drag-able portion should now take up the height of the container
Should prevent infuriating not dragging situations
- Now correctly resets to the value from the start of the drag on cancel
=> InputNumberUI: Fix Fitt's Law and Cancel

library/built-in/_prefabs/prefab_detailer.ts, library/built-in/_prefabs/prefab_prompt_list.ts, library/built-in/_prefabs/prefab_sampler.ts, src/core/litegraphToPrompt.ts, src/runtime/RuntimeVideo.ts
Found a better workflow for eye detailing
Added a prompt_list prefab, but don't have time to split off a separate example of use, sorry
Litegraph change was because import was erroring out on workflows that had optional inputs. Could be a one-off, so reject that one if you want.
RuntimeVideo was an issue with the images coming out slightly out of order
=> eye detailer improvements, prompt list prefab, and video tweaks

src/panels/Panel_Icons/Panel_Icons.tsx
- Icons can now be clicked to copy text
- Show the most recently copied icons at the top
- Filter is toggle-able without needing to change the query
- Removed displaying icon names.
(This is useless now that you can copy it.)
=> Panel_Icons: Overhaul

_mac-linux-cleanup.sh, _mac-linux-install.sh
- Fixes the icon not being used on Wayland, as there are no protocols to allow them to set this programmatically.
- Adds 2 entries to launch from launchers that look for .desktop files.
- One that launches Cushy normally, and one that starts the dev script.
- Not heavily tested on Wayland sessions other than KDE.
=> Wayland: Make .desktop file entries

src/csuite/model/TESTS/default-values.test.ts
For now, this just makes it obvious that `Field_selectMany`'s handling of its config's `default` is broken
I'm actually not sure how to fix it, since the value encoded in its serial is not marked optional
=> Fix select many default values + add tests
