rvion/CushyStudio

- src/controls/askv2.ts
- src/ui/AskInfoUI.tsx
- src/ui/WebviewPlacePoints.tsx
- src/ui/WebviewPlacePoints_old.tsx
Added functionality to prompt the user to place a bunch of points for the sam nodes from the WAS suite.
> SAM point placement

- docs/FAQ.md
- I added [alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts) to notify it's a draft and where you request to be contacted by cloud providers or sponsors.
- I left the Question and main answer as-is and made the more detailed answer collapsible
> Clean FAQ.md

- src/wildcards/wildcards.gen.ts
Fixed some regular expressions in the wildcard generator.
Made the strings into global regular expressions.
> Fixed Regular Expressions

- package-lock.json
- src/front/updater.ts
Added some code to check that the folder we are looking for exists. The error I was experiencing is shown below in the image.
> Fixed bug causing ui to not load

- index.html
- src/prompter/nodes/BooruNode.tsx
- src/prompter/nodes/EmbeddingNode.tsx
- src/prompter/nodes/LoraNode.tsx
- src/prompter/nodes/WildcardNode.tsx
removed the "space" that followed special prompt nodes to allow for better user formatting of their prompt
> Removed the right margin on prompt "Special" nodes

- src/widgets/galleries/dnd.ts
Nothing was being displayed after an image drop, this resolves that issue
> FIX display image after drop

- src/utils/ffmpeg/ffmpegScripts.ts
It seems ffmpeg expects relative paths for the frame images.
https://github.com/rvion/CushyStudio/issues/96
> FIX ffmpeg frame paths

- _windows_START.bat
Added path quotes to the windows start .bat as well. Only caught the install on the other PR
> path quotes

- src/panels/host/HostUI.tsx
Settings was not allowing edit of model path
> Fix model path in settings

- _windows-install.bat
> FIX windows install

- library/built-in/_prefabs/ControlNet/ipAdapter/_ipAdapterModelList.ts
- library/built-in/_prefabs/ControlNet/ipAdapter/_ipAdapterUtils.ts
- library/built-in/_prefabs/ControlNet/ipAdapter/prefab_ipAdapter_base.ts
- library/built-in/_prefabs/ControlNet/ipAdapter/prefab_ipAdapter_base_standalone.ts
- library/built-in/_prefabs/ControlNet/ipAdapter/prefab_ipAdapter_face.ts
- library/built-in/_prefabs/ControlNet/prefab_cnet_canny.ts
- library/built-in/_prefabs/ControlNet/prefab_cnet_depth.ts
- library/built-in/_prefabs/ControlNet/prefab_cnet_lineart.ts
- library/built-in/_prefabs/ControlNet/prefab_cnet_normal.ts
- library/built-in/_prefabs/ControlNet/prefab_cnet_openPose.ts
- library/built-in/_prefabs/ControlNet/prefab_cnet_scribble.ts
- library/built-in/_prefabs/ControlNet/prefab_cnet_softEdge.ts
- library/built-in/_prefabs/ControlNet/prefab_cnet_tile.ts
- library/built-in/_prefabs/prefab_cnet.ts
Revise the controlnet interface to group and hide unnecessary settings better and make use of the new choice visual for tab selection.
> Controlnet Interface Cleanup

- src/controls/shared/ListControlsUI.tsx
- src/theme/theme.css
Fixes some controls appearing over the Draft Header
Gives groups/panels a tiny bit of padding so other widgets aren't touching the edges.
> Minor CSS changes

- src/app/layout/FavBar.tsx
- src/theme/theme.css
Also adds a few MENU-* CSS rules
These could help with consistency for menus accross the program later on
> UI: Make FavBar pretty

- _windows-cleanup.bat
- _windows-install.bat
- _windows-reset-db.bat
- _windows-start-dev.bat
- _windows-start.bat
- _windows-update.bat
Learning myself a windows batch. I briefly tested everything on my own machine and thing seem to work.
> Improve consistency and style of windows batch

- _windows-install.bat
- _windows-reset-db.bat
- _windows-start-dev.bat
- _windows-start.bat
- _windows-update.bat
It seems like `!` is not a cool thing in batch if statements, and also that the things being compared should be quoted.
I also think I fixed the icon patching for windows.
> Fixing batch scripts a little more

- src/controls/widgets/prompt/plugins/Plugin_AdjustWeights.tsx
Using weighted.from broke drag to change value for all but the last one
> Plugin_AdjustWeights: Use index for keys

- library/built-in/_ipAdapter/_ipAdapterUtils.ts
- library/built-in/_ipAdapter/prefab_ipAdapter_base.ts
- library/built-in/_ipAdapter/prefab_ipAdapter_base_standalone.ts
- library/built-in/_ipAdapter/prefab_ipAdapter_face.ts
Mostly hacks to get it to work again without implementing new features or interface
> IPAdapterV2 fixes

- library/built-in/_ipAdapter/prefab_ipAdapter_base.ts
- library/built-in/_ipAdapter/prefab_ipAdapter_face.ts
I guess I hadn't updated yet. Looks like he added another setting, so I wired the default
> IpAdapterV2 fix

- library/built-in/_ipAdapter/prefab_ipAdapter_base_standalone.ts
working on a better IPAdapter, but for now just hack fixed this
> IPAdapter standalone hack fix

- library/built-in/CushyDiffusion.ts
- library/built-in/_ipAdapter/_ipAdapterModelList.ts
- library/built-in/_ipAdapter/_ipAdapterUtils.ts
- library/built-in/_ipAdapter/prefab_ipAdapter_baseV2.ts
- library/built-in/_ipAdapter/prefab_ipAdapter_base_standalone.ts
- library/built-in/_ipAdapter/prefab_ipAdapter_faceV2.ts
- library/built-in/_prefabs/prefab_detailer.ts
- library/built-in/_prefabs/prefab_sampler.ts
1. IPAdapter now loads more like the comfyUI node approach, with much simpler model selection. It is only included as a stand-alone. The old version won't really work with the version in the controlnet selection.
2. FaceID - basically same changes as IPAdapter
3. Detailer - added a really rough Eye enhancer. Works okay when the face is big. Also added an optional sam model to crop bounding boxes.
4. Updated ui to take advantage of summary option
5. Modified sampler ui to allow passing defaults
> IPAdapterV2, FaceIDV2, Detailer Eyes

- library/built-in/_prefabs/prefab_latent_v3.ts
- src/controls/widgets/image/WidgetImage.tsx
- src/controls/widgets/image/WidgetImageUI.tsx
- src/controls/widgets/resizableFrame/resizableFrameUI.tsx
- src/panels/PanelHeader.tsx
- src/panels/Panel_Models/Panel_Models.tsx
- src/widgets/galleries/ImageUI.tsx
- Adds a new ResizableFrame component that allows things to expand
a bit more vertically if the user wants.
- Move everything to that.
Did not move the suggestion thing, I don't know what it does.
> WidgetImageUI: Overhaul

- src/controls/fields/image/WidgetImageUI.tsx
@birdddev :
> Saving constantly when making minor adjustments and just the issues with DnD on Wayland are so annoying. This is just better, should be able to paste in to this widget anyways.
> WidgetImageUI: Add way to paste from clipboard

- library/built-in/CushyDiffusionUI.ts
- library/built-in/_controlNet/prefab_cnet.ts
- library/built-in/_ipAdapter/_ipAdapterUtils.ts
- library/built-in/_ipAdapter/prefab_ipAdapter_baseV2.ts
- library/built-in/_ipAdapter/prefab_ipAdapter_faceV2.ts
- library/built-in/_prefabs/_prefabs.ts
- library/built-in/_prefabs/prefab_3dDisplacement.ts
- library/built-in/_prefabs/prefab_mask.ts
- library/built-in/_prefabs/prefab_rembg.ts
- library/built-in/_prefabs/prefab_sampler_advanced.ts
- library/built-in/_prefabs/prefab_upscaleWithModel.ts
- library/built-in/_prefabs/saveSmall.ts
- src/csuite/fields/size/ResolutionState.tsx
- src/csuite/fields/size/WidgetSizeTypes.ts
- src/csuite/fields/size/WidgetSizeUI.tsx
- src/models/Draft.ts
--attempt to fix the restart timer
--icons and colors for cushyDiffusions and prefabs
--add SDXL resolutions from Fooocus that are supposedly closer to SDXL training dimensions that use pixel-specific dimensions rather than ratio
--changed ipadapterV2 ui to be a single unified list of images rather than split into first and extra
--added sampler_advanced prefab that has lots of custom sampler selections for more complex sampler control, in particular AYS (align your step) and some other experimental comfyui guidance methods such as Dual CFG and PerpNeg
> restart timer, Icons and colors for prefabs, fix for ipadapterv2, advanced sampler, aspect ratio

- src/csuite/badge/BadgeListUI.tsx
- src/models/MediaImage.ts
- src/panels/Panel_ViewImage.tsx
--I wanted a way to directly edit tags on the output image
@rvion This is just the best I could come up with. Still figuring out the whole react thing. I think it probably breaks your BadgeListUI being more generic, and the visual on it is pretty intrusive and terrible. So please feel free to just rework the whole thing. 
https://github.com/rvion/CushyStudio/assets/153457815/2e519a35-ae86-4a8e-987d-fde07c99775f
> add tag edit to output bar

- src/config/ConfigFile.ts
- src/models/MediaImage.ts
- src/panels/ImageDropdownUI.tsx
- src/panels/Panel_Config.tsx
--Add a context option to save a copy to a configurable local favorites folder
> Local Favorites Folder

- src/csuite/model/TESTS/serial.test.ts
I'm opening this as a "TDD": Test driven discussion
> Unexpected behavior with snapshots
